example/lib/admin_elf_example_web/router.ex
defmodule AdminElfExampleWeb.Router do
  use AdminElfExampleWeb, :router

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", AdminElfExampleWeb do
    pipe_through :api

    resources "/brands", BrandController, only: [:index, :show]
  end

  forward "/admin", AdminElf.Plug, admin: AdminElfExampleWeb.Admin


  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through [:fetch_session, :protect_from_forgery]
      live_dashboard "/dashboard", metrics: AdminElfExampleWeb.Telemetry
    end
  end
end

lib/admin_elf_web/router.ex
defmodule AdminElfWeb.Router do
  use AdminElfWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AdminElfWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/:resource_id", ResourceController, :index
    # POST /:resource_id/:item_id/custom-action/:action
    # POST /:resource_id/custom-action/:action
    # GET /:resource_id/:item_id
    # GET /:resource_id/new
    # GET /:resource_id/:item_id/edit
    # POST /:resource_id
    # PATCH /:resource_id/:item_id
    # DELETE /:resource_id/:item_id
  end

  # Other scopes may use custom stacks.
  # scope "/api", AdminElfWeb do
  #   pipe_through :api
  # end
end

lib/admin_elf_web/templates/resource/index.html.eex
<div class="bg-white shadow-md rounded-md p-8 mb-4">
  <h2 class="flex items-center gap-3 text-4xl">
    <%= resource_icon(@conn, @resource_id, width: "32", height: "32") %>
    <%= @conn |> resource_plural_name(@resource_id) |> capitalize() %>
  <h2>
</div>

<div class="flex flex-col 2xl:flex-row-reverse">
  <% resource_filters = resource_filters(@conn, @resource_id) %>

  <%= if resource_filters != [] do %>
    <form
      method="get"
      action="<%= Routes.resource_index_path(@conn, @resource_id, Map.delete(@params, :filter)) %>"
      class="bg-white shadow-md rounded-md p-8 mb-4 2xl:ml-4 h-full 2xl:w-80"
    >
      <%= for filter <- resource_filters do %>
        <%= case filter.type do %>
          <% :text -> %>
            <div class="mb-4">
              <label>
                <%= filter.label %>
                <input type="text" name="filter[<%= filter.name %>]" value="<%= @params.filter[filter.name] %>" class="form-input mt-1 block w-full border rounded p-2" />
              </label>
            </div>

          <% :radio -> %>
            <div class="mb-4">
              <label><%= filter.label %></label>
              <div class="mt-2">
                <%= for {value, label} <- filter.options do %>
                  <label class="inline-flex items-center mr-6">
                    <input type="radio" class="form-radio border" name="filter[<%= filter.name %>]" value="<%= value %>" <%= if @params.filter[filter.name] == value, do: "checked" %>/>
                    <span class="ml-2"><%= label %></span>
                  </label>
                <% end %>
              </div>
            </div>

          <% :boolean -> %>
            <div class="block mb-4 gap-4" x-data="{ hasValue: <%= is_boolean(@params.filter[filter.name]) %> }">
              <label class="flex items-center">
                <%= filter.label %>
                <span
                  class="text-red-400 hover:text-red-500 ml-1 cursor-pointer"
                  x-show="hasValue"
                  x-on:click="$refs.trueCheckbox.checked = false; $refs.falseCheckbox.checked = false; hasValue = false"
                >
                  <%= feather_icon(@conn, "trash", size: 16) %>
                </span>
              </label>
              <div class="mt-2">
                <label class="inline-flex items-center mr-6">
                  <input
                    type="radio"
                    class="form-radio border"
                    name="filter[<%= filter.name %>]"
                    value="true"
                    x-ref="trueCheckbox"
                    x-on:click="hasValue = true"
                    <%= if @params.filter[filter.name] == true, do: "checked" %>
                  />
                  <span class="ml-2">Yes</span>
                </label>

                <label class="inline-flex items-center mr-6">
                  <input
                    type="radio"
                    class="form-radio border"
                    name="filter[<%= filter.name %>]"
                    value="false"
                    x-ref="falseCheckbox"
                    x-on:click="hasValue = true"
                    <%= if @params.filter[filter.name] == false, do: "checked" %>
                  />
                  <span class="ml-2">No</span>
                </label>
              </div>
            </div>

          <% :select -> %>
            <div class="block mb-4">
              <label><%= filter.label %></label>
              <select class="form-select mt-1 block w-full border rounded" name="filter[<%= filter.name %>]">
                <option value="">...</option>
                <%= for {value, label} <- filter.options do %>
                  <option value="<%= value %>" <%= if @params.filter[filter.name] == value, do: "selected" %>><%= label %></option>
                <% end %>
              </select>
            </div>

          <% :checkboxes -> %>
            <div class="mb-4 gap-4">
              <label><%= filter.label %></label>

              <div class="flex flex-wrap gap-4">
              <%= for {value, label} <- filter.options do %>
                <label class="flex items-center">
                  <input type="checkbox" value="<%= value %>" class="form-checkbox border" name="filter[<%= filter.name %>][]" <%= if value in (@params.filter[filter.name] || []), do: "checked" %>>
                  <span class="ml-2"><%= label %></span>
                </label>
              <% end %>
              </div>
            </div>
        <% end %>
      <% end %>

      <div class="flex gap-3 items-between">
        <button type="submit" class="px-8 py-2 border border-transparent text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700">
          Search
        </button>

        <a
          class="px-8 py-2 border border-transparent text-base font-medium rounded-md text-gray-800 bg-gray-200 hover:bg-gray-300"
          href="<%= Routes.resource_index_path(@conn, @resource_id, Map.delete(@params, :filter)) %>"
        >
          Clear
        </a>
      </div>
    </form>
  <% end %>

  <% ids = Enum.map(@items, &resource_item_id(@conn, @resource_id, &1)) %>
  <div class="flex-grow bg-white shadow-md rounded-md p-8" x-data="{ allItems: <%= Jason.encode!(ids) %>, selected: [], allChecked: false }">
    <div class="overflow-x-auto">
      <table class="table-auto shadow-md w-full">
        <thead>
          <tr>
            <th class="border text-left w-1">
              <div class="px-6 py-2">
                <input type="checkbox" class="cursor-pointer" x-on:change="allChecked ? selected = allItems : selected = []" x-model="allChecked"/>
              </div>
            </th>
            <%= for column <- resource_index_table(@conn, @resource_id) do %>
              <th class="border text-left">
                <%= if column.order do %>
                  <a class="flex items-center px-6 py-2" href="<%= update_resource_order(@conn, @resource_id, @params, column.field) %>">
                    <span><%= column.label %></span>
                    <%= cond do %>
                      <% not is_nil(@params.order) and @params.order.field == column.field and @params.order.direction == :asc -> %>
                        <%= feather_icon(@conn, "chevron-down") %>
                      <% not is_nil(@params.order) and @params.order.field == column.field and @params.order.direction == :desc -> %>
                        <%= feather_icon(@conn, "chevron-up") %>
                      <% true -> %>
                        <%= feather_icon(@conn, "minus", stroke_width: "2", width: "16", height: "16") %>
                    <% end %>
                  </a>
                <% else %>
                  <div class="px-6 py-2">
                    <%= column.label %>
                  </div>
                <% end %>
              </th>
            <% end %>
            <th class="border text-left w-1">
              <div class="px-6 py-2">
                Actions
              </div>
            </th>
          </tr>
        </thead>

        <tbody>
          <%= for item <- @items do %>
            <tr class="hover:bg-blue-50 even:bg-gray-100">
              <td class="border px-6 py-2">
                <input
                  type="checkbox"
                  class="cursor-pointer"
                  name="batch_action[]"
                  value="<%= resource_item_id(@conn, @resource_id, item) %>"
                  x-model="selected"
                  x-on:click="allChecked = false"
                />
              </td>
              <%= for column <- resource_index_table(@conn, @resource_id) do %>
                <td class="border px-6 py-2"><%= column.value.(item) %></td>
              <% end %>
              <td class="border px-6 py-2">
                <div class="flex gap-2 justify-center">
                  <a href="#" class="text-gray-600 hover:text-gray-800">
                    <%= feather_icon(@conn, "file-text") %>
                  </a>
                  <a href="#" class="text-blue-600 hover:text-blue-800">
                    <%= feather_icon(@conn, "edit") %>
                  </a>
                  <a href="#" class="text-red-600 hover:text-red-800">
                    <%= feather_icon(@conn, "trash-2") %>
                  </a>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="flex items-center justify-between mt-4">
      <div class="text-gray-600">
        <%= if @count < @params.limit do %>
          Showing <%= @count %> items.
        <% else %>
          Showing <%= (@params.page - 1) * @params.limit + 1 %>-<%= min(@params.page * @params.limit, @count) %> of <%= @count %> items.
        <% end %>
      </div>

      <%= render_partial("pagination.html", conn: @conn, params: @params, count: @count, route: &Routes.resource_index_path(@conn, @resource_id, %{@params | page: &1})) %>
    </div>
  </div>
</div>